//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class KeyButton
{
	public delegate void Action();
	
	private bool pressed;
	private bool touched  = false;
	private bool buttonPressed;
	private bool keyPressed;
	
	public Rect rectangle;
	private string name;
	public event Action action;
	public event Action releaseAction;
	private KeyCode keyCode;

	private Vector2 v1 = Vector2.zero;

	public KeyButton(Rect rectangle , string name, KeyCode keyCode)
	{
		this.rectangle = rectangle;
		this.name = name;
		this.keyCode = keyCode;
	}
	
	public void PerformUpdate(){
		if (Input.GetKeyDown(keyCode)){
			keyPressed = true;
		}else if (Input.GetKeyUp( keyCode) ){
			keyPressed = false;
			releaseAction();
		}
		
		if ( keyPressed || touched ) {
			action();
		}

		List<iPhoneTouch> goodIphoneTouches = TouchControl.getGoodIphoneTouches();
		if (goodIphoneTouches.Count == 1){
			iPhoneTouch touch = goodIphoneTouches[0];
			v1 = new Vector2 ( touch.position.x, Screen.height - touch.position.y );
			//Camera cam = GameObject.Find("Screen Camera").camera;
			//Debug.Log("v1 = " + v1 + ",cam.pixelWidth  = " + cam.pixelWidth + ",cam.pixelHeight  = " + cam.pixelHeight );
			if ( !touched && rectangle.Contains(v1) ){
				Debug.Log("TouchDown");
				touched = true;
			}
		}else if ( touched && goodIphoneTouches.Count == 0 ){
			Debug.Log("TouchUp");
			touched = false;
			releaseAction();
		}

		if (!touched){
			Vector2 v = new Vector2 ( Input.mousePosition.x, Screen.height - Input.mousePosition.y );
			if ( Input.GetMouseButtonDown(0) && rectangle.Contains(v) ){
				Debug.Log("ButtonDown");
				pressed = true;
			}else if (pressed &&  ( Input.GetMouseButtonUp(0) || !rectangle.Contains(v) ) ){
				Debug.Log("ButtonUp");
				pressed = false;
				releaseAction();
			}
		}
	}
	
	public void PerformOnGui()
	{
		GUI.Button( rectangle , name );
		if (pressed){
			action();
		}
	}
}


