//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class KeyButton
{
	public delegate void Action();
	
	private bool pressed;
	private bool buttonPressed;
	private bool keyPressed;
	
	private Rect rectangle;
	private string name;
	public event Action action;
	public event Action releaseAction;
	private KeyCode keyCode;
	
	
	
	public KeyButton(Rect rectangle , string name, KeyCode keyCode)
	{
		this.rectangle = rectangle;
		this.name = name;
		this.keyCode = keyCode;
	}
	
	public void PerformUpdate(){
		if (Input.GetKeyDown(keyCode)){
			keyPressed = true;
		}else if (Input.GetKeyUp( keyCode) ){
			keyPressed = false;
			releaseAction();
		}
		
		if ( pressed || keyPressed ) {
			action();
		}
	}
	
	public void Perform()
	{
		bool turnedOff = false;
		if ( GUI.RepeatButton( rectangle , name ) ){
			buttonPressed = true;
			pressed = true;
		}else if (buttonPressed) {
			turnedOff = true;
			buttonPressed = false;
		}
		
		if (pressed && !buttonPressed && !turnedOff){
			releaseAction();
			pressed = false;
		}
	}
}


