//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


public class PlanetInfos
{
	private static Dictionary<string, string> info = new Dictionary<string,string>(){
		{"Sun", 
				"<b>Rovníkový priemer</b>\t\t: 1.39 M km\n"+
				"<b>Povrchová gravitácia</b>\t: 274 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: 5505°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 25 dní\n"+
				"<b>Doba obehu galaxie</b>\t\t: 23 M rokov\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 58 M km\n"+
				"<b>od centra galaxie</b>\n"+
				"\n<b>Základ</b> : Slnko je hviezda v strede slnečnej , \n"+
				"sústavy pričom jej hmotnosť dosahuje približne  \n"+
				"99,86% celkovej hmotnosti celej slnečnej sústavy\n"+
				"\n<b>Zloženie</b> : Zhruba tri štvrtiny hmotnosti Slnka \n"+
				"tvorí vodík, zvyšok prevažne hélium. Iba 1.69% Slnka \n"+
				"sa skladá z  tažších prvkov ako je uhlík, železo, \n"+
				"neón a kyslík\n"+
				"\n<b>Vzdialenosť</b> : Priemerná vzdialenoť Slnka od Zeme je \n"+
				"približne 149.600.000 km (1 AU ), Svetlu trvá v priemere \n"+
				"asi 8 minút a 192 sekúnd pokým sa dostane na Zem\n"+
				"\n<b>Galaxia</b> : Pokým v minulosti prevládal názor, že \n"+
				"Slnko je relatívne bezvýznamná hviezda, v súčasnosti je  \n"+
				"považované za jasnejšie než 85% hviezd Mliečnej dráhy.   \n"+
				"Slnko je v  rámci Mliečnej umiestnené približne v 2/3\n"+
				"vzdialenosti od centra \n"
		},
		{"Mercury", 
				"<b>Rovníkový priemer</b>\t\t: 4880 km\n"+
				"<b>Povrchová gravitácia</b>\t: 3.7 m/s²\n"+
				"<b>Teplota - Deň</b>\t\t\t\t\t: 473°C\n"+
				"<b>Teplota - Noc</b>\t\t\t\t\t: -183°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 59 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 88 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 58 M km\n"+
				"\n<b>Základ</b> : Merkúr je najvnútornejšia a najmenšia \n"+
				"planéta slnečnej sústavy. Vzhľadom k tomu , že nemá \n"+
				"takmer žiadnu atmosféru, ktorá by udržala teplo, povrch \n"+
				"Merkúra zaznamenáva najvačšie teplotné rozdiely zo \n"+
				"všetkých planét\n"+
				"\n<b>Pozorovania</b> : Merkúr sa z pohľadu Zeme javí ako \n"+
				"večerná alebo ranná hviezda, ale z dôvodu blízkosti Slnka \n"+
				"je ho veľmi tažké vidieť. Napriek tomu môže byť Merkúr \n"+
				"pozorovaný dvakrát ročne: na jar za súmraku a na jeseň \n"+
				"pred svitaním"
		},
		{"Venus", 
				"<b>Rovníkový priemer</b>\t\t: 12 110 km\n"+
				"<b>Povrchová gravitácia</b>\t: 8.9 m/s²\n"+
				"<b>Teplota - Deň</b>\t\t\t\t\t: 462°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 243 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 225 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 108 M km\n"+
				"\n<b>Základ</b> : Aj keď má Venuša veľmi podobnú \n"+
				"veľkosť a vnútornú štruktúru ako Zem, jej vulkanický\n"+
				"povrch spolu s extrémne horúcou atmosférou z nej robia\n"+
				"jedno z najviac nehostinných miest v Slnečnej sústave\n"+
				"\n<b>Atmosféra</b> : Husté mraky kyseliny sírovej a prachu\n"+
				"odrážajú väčšinu slnečného svetla späť do vesmíru, zatiaľ \n"+
				"čo oxid uhličitý zachytáva slnečné svetlo v atmosfére, čo\n"+
				"spôsobuje skleníkový efekt. Atmosférický tlak na povrchu je\n"+
				"92 krát väčší než na Zemi\n"+
				"\n<b>Pozorovania</b> : Venuša je jedým z najjasnejších \n"+
				"objektov nočnej oblohy - druhá po Mesiaci. Objavuje sa \n"+
				"buď ako večerná alebo ranná hviezda \n"
		},
		{"Earth", 
				"<b>Rovníkový priemer</b>\t\t: 12 756 km\n"+
				"<b>Povrchová gravitácia</b>\t: 9.8 m/s²\n"+
				"<b>Teplota</b>\t\t\t\t\t\t\t: 15°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 23h 56m\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 1 rok\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 150 M km\n"+
				"\n<b>Základ</b> : Naša domovská planéta je najhustejšia \n"+
				"z ôsmich planét v Slnečnej sústave. Je taktiež najväčou\n"+
				"zo štyroch terestriálnych planét\n"+
				"\n<b>Povrch</b> : 71% povrchu je pokrytého slanou vodou\n"+
				"z oceánov a zvyšných 30% je vyzdvihnutých do siedmich\n"+
				"kontinentálnych pevnín. Najvrchnejšia časť Zeme je \n"+
				"rozdelená na niekoľko pevných častí, tektonických platní,\n"+
				"ktoré sa pohybujú po povrchu milióny rokov\n"+
				"\n<b>Magnetické pole</b> : Magnetické pole Zeme sa \n"+
				"generuje v roztavenej časti vonkajšieho jadra planéty,\n"+
				"rozširuje sa smerom von a vytvára magnetosféru: \n"+
				"bariéru obklopujúcu Zem, ktorá vychyľuje častice \n"+
				"slnečného vetra a chráni Zem pred slnečnou radiáciou\n"
		},
		{"Moon", 
				"<b>Rovníkový priemer</b>\t\t: 3 476 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.62 m/s²\n"+
				"<b>Teplota</b>\t\t\t\t\t\t\t: -23°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 27 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 27 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 384 000 km\n"+
				"\n<b>Základ</b> : Mesiac je jediný prirodzený satelit \n"+
				"Zeme. Popri Slnu nám Mesiac na Zem aj najväčší vplyv, \n"+
				"ktorý sa prejavuje najmä prílivom a odlivom\n"+
				"\n<b>Hmotnosť</b> : Mesiac je najväčší prirodzený satelit\n"+
				"vzhľadom k veľkosti materskej planéty - z 27% priemeru a\n"+
				"60% hustoty Zeme. Súčasne je Mesiac väčší ako Pluto\n"+
				"\n<b>Pôvod</b> : V súčasnosti prevláda hypotéza, že Mesiac\n"+
				"vznikol ako výsledok zrážky telesa veľkosti Marsu s novo,\n"+
				"sa formujúcou protozemou. Materiál vymrštený pri tejto\n"+
				"zrážke postupným prirastaním vytvoril Mesiac približne\n"+
				"pred 4.53 miliardami rokov\n"+
				"\n<b>Pozorovanie</b> : Mesiac je najjasnejší objekt na oblohe\n"+
				"po Slnku,aj keď jeho povrch je v skutočnosti tmavý a odráža \n"+
				"iba 7% percent svetla, ktoré naň dopadá. Súčasná orbitálna \n"+
				"vzialenosť Mesiaca spôsobuje, že sa na oblohe javí takmer  \n"+
				"v rovnakej veľkosti ako Slnko\n"
		},		
		{"Mars", 
				"<b>Rovníkový priemer</b>\t\t: 6 794 km\n"+
				"<b>Povrchová gravitácia</b>\t: 3.7 m/s²\n"+
				"<b>Teplota-Leto</b>\t\t\t\t\t: 17°C\n"+
				"<b>Teplota-Zima</b>\t\t\t\t\t: -140°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 1.03 deň\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 1.88 rok\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 228 M km\n"+
				"\n<b>Základ</b> : Mars je štvrtá planéta a druhá \n"+
				"najmenšia v slnečnej sústave. Červenkastý nádych \n"+
				"povrchu je spôsobený oxidom železa (hrdzou)\n"+
				"\n<b>Povrch</b> : Povrch Marsu je značne rozmanitý, s\n"+
				"vysokými sopkami a veľkým systémom kaňonov. Zo \n"+
				"všetkých má najvyššiu horu - Olympus Mons a \n"+
				"najväčší kaňon, Valles Marines\n"+
				"\n<b>Voda</b> : Existujú presvedčivé dôkazy, že na Marse\n"+
				"bola kedysi atmosféra oveľa hustejšia kao teraz a voda\n"+
				"tiekla voľne po povrchu. K dispozícii je tiež stále viac\n"+
				"dôkazov, že veľká časť tejto vody sa nachádza stále v\n"+
				"podzemí\n"+
				"\n<b>Misie</b> : Mars je predmeto intenzívneho výskumu, s\n"+
				"dvoma sondami na povrchu (Opportunity a Curiosity) a\n"+
				"s troma misiami na obežnej dráhe. \n"
		},
		{"Jupiter", 
				"<b>Rovníkový priemer</b>\t\t: 142 800 km\n"+
				"<b>Povrchová gravitácia</b>\t: 25 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -120°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 09h 55m deň\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 11.9 rokov\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 778 M km\n"+
				"\n<b>Základ</b> : Jupiter je najvačšia planéta slnečnej \n"+
				"sústavy s hmotnosťou 2.5x väčšou ako všetky ostatné\n"+
				"planéty dohromady\n"+
				"\n<b>Atmosféra</b> :Jupiter sa otáća okolo svojej osi\n"+
				"rýchlejšie ako akákoľvek iná planéta. Vzhľadom k tejto\n"+
				"rotácie atmosféra podlieha silným vetrom, ktoré spôsobujú,\n"+
				"že sa atmosféra formuje do zreteľných farebných skupín\n"+
				"ako sú víry a gigantické anticyklonálne búrky\n"+
				"\n<b>Pozorovanie</b> : Jupiter je štvrtým najjasnejším\n"+
				"objektom na oblohe po Slnku, Mesiaci a Venuši. Kedže\n"+
				"obežná dráha Jupitera je vonkajšia voči obežnej dráhe\n"+
				"Zeme, pri pozorovaní teleskopmi sa planéta javí takmer\n"+
				"vždy úplne osvetlená\n"
		},
		{"Io", 
				"<b>Rovníkový priemer</b>\t\t: 3 643 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.8 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -152°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 1.77 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 1.77 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 422 000 km\n"+
				"\n<b>Základ</b> : Io je štvrtý najväčší mesiac v \n"+
				"slnečnej sústave. Má vyše 400 aktívnych sopiek, čo\n"+
				"z neho robí vulkanicky najaktívnejšie teleso v \n"+
				"slnečnej sústave. Sopečné oblaky pritom stúpajú\n"+
				"až do výšky 300 km nad povrchom\n"+
				"\n<b>Povrch</b> :Vulkanické oblaky a toky lávy pokrývajú \n"+
				"povrch mesiaca žltými, červenými, bielymi a čiernymi\n"+
				"žlúčeninami síry. Na povrchu sa tiež nachádza viac ako\n"+
				"100 vrchov, pričom niektoré sú vyššie ako Mount Everest\n"+
				"\n<b>Elektrický generátor</b> :Io pretína magnetické\n"+
				"siločiary Jupitera, čo vytvára z tohto mesiaca silný\n"+
				"elektrický generátor. Elektrický prúd s hodnotou 3 mil\n"+
				"ampérov prúdi k povrchu Jupitera a vytvára blesky vo\n"+
				"vrchnej časti jeho atmosféry\n"
		},
		{"Europa", 
				"<b>Rovníkový priemer</b>\t\t: 3 122 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.31 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -171°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 3.6 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 3.6 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 671 000 km\n"+
				"\n<b>Základ</b> :Aj keď je Európa najmenší zo \n"+
				"štyroch galileiho mesiacov,ide súčasne o šiesty\n"+
				"najväčší mesiac v slnečnej sústave. Európa môže\n"+
				"predstavovať najbližšie miesto k Zemi, kde by\n"+
				"vedci mohli nájsť život\n"+
				"\n<b>Océan</b> :Pod ľadovou kôrou Európy existuje \n"+
				"teoreticky obrovský oceán. Hoci je Európa ďaleko od\n"+
				"Slnka silné gravitačné vlny Jupitera mohli vytvoriť\n"+
				"vnútorne teplo potrebné na udržanie kvapalnej vody \n"+
				"\n<b>Život</b> :Nedávny objav vodných gejzírov a \n"+
				"detekcia ílových minerálov naznačujú, že by v rámci\n"+
				"podpovrchového života mohli existovať základné formy\n"+
				"vodného života\n"
		},		
		{"Ganymede", 
				"<b>Rovníkový priemer</b>\t\t: 5 268 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.43 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -163°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 7.2 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 7.2 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 1.07 M km\n"+
				"\n<b>Základ</b> :Ganymedes je najvačším mesiacom\n"+
				"v Slnečnej sústave. Je väčší ako Merkúr a len o \n"+
				"málo menší ako Mars. Ak by Ganymede namiesto \n"+
				"Jupitera obiehal okolo Slnka bol by klasifikovaný\n"+
				"ako planéta\n"+
				"\n<b>Magnetosféra</b> :Je jediný mesiac v slnečnej \n"+
				"sústave, u ktorého bola zistená Magnetosféra\n"
		},
		{"Callisto", 
				"<b>Rovníkový priemer</b>\t\t: 4 821 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.24 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -172°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 16.7 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 16.7 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 1.88 M km\n"+
				"\n<b>Základ</b> :Ganymedes je najvačším mesiacom\n"+
				"v Slnečnej sústave. Je väčší ako Merkúr a len o \n"+
				"málo menší ako Mars. Ak by Ganymede namiesto \n"+
				"Jupitera obiehal okolo Slnka bol by klasifikovaný\n"+
				"ako planéta\n"+
				"\n<b>Krajina</b> :Callisto nevykazuje žiadne známky \n"+
				"zmeny povrchu od doby, kedy jeho povrch vytvarovali\n"+
				"vplyvy iných telies. Z toho dôvodu má najstaršiu krajinu\n"+
				"v slnečnej sústave s vekom asi 4 mld rokov\n"
		},
		{"Saturn", 
				"<b>Rovníkový priemer</b>\t\t: 120 600 km\n"+
				"<b>Povrchová gravitácia</b>\t: 10.4 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -125°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 10h 39m\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 29 rokov\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 1 427 M km\n"+
				"\n<b>Základ</b> :Saturn je šieta planéta od Slnka\n"+
				"a druhá najvačšia planéta slnečnej sústavy. Až do \n"+
				"vynálezu moderného ďalekohľadu bol Saturn považovaný \n"+
				"za najvzdialenejšiu známu planétu\n"+
				"\n<b>Hmotnosť</b> :Hoci Saturn je druhý najvačšií\n"+
				"je to najmenej hustá planéta zo všetkých v slnečnej \n"+
				"sústave. Má iba jednu osminu hustoty Zeme. Je to tiež \n"+
				"jediná planéta, ktorá má menšiu hustotu ako voda\n"+
				"\n<b>Prstenec</b> :Aj keď všetky plynné obri majú \n"+
				"prstencové systémy, sys´tém prstencov Saturnu je väčší\n"+
				"a viditeľnejší než akýkoľvek iný v slnečnej sústave. \n"+
				"Prstence sú zložené z ľadových kryštälov a úlomkov hornín\n"+
				"s veľkosťou až po časti vo veľkosti hory.\n"+
				"\n<b>Pozorovanie</b> :Saturn sa pri svojom pozorovaní \n"+
				"nočnej oblohy voľným okom javí ako jasný žltkastý bod.\n"+
				"Pri minimálne 30 násobnom priblížení je pozorovať\n"+
				"aj prstence.\n"
		},
		{"Enceladus", 
				"<b>Rovníkový priemer</b>\t\t: 504 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.11 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -200°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 1.37 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 1.37 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 238 000 km\n"+
				"\n<b>Základ</b> :Saturnov je šiety najvačší mesiac\n"+
				"Má najvačšie známe albedo zo všetkých \n"+
				"objektov v slnečnej sústave, pričom odráža takmer\n"+
				"100% prijatého slnečného svetla\n"+
				"\n<b>Kryovulkány</b> :Kryovulkány na južnom póle \n"+
				"spôsobujú výtrysky ľadových gejzírov do priestoru \n"+
				"Predpokladá sa, že celý Saturnov E prstenec bol vytvorený \n"+
				"z týchto častíc ladu\n"+
				"\n<b>Voda</b> :Vyzerá to tak, že Enceladus má pod \n"+
				"ľadovým povrchom tekutú vodu. Toto môže byť spôsobené\n"+
				"vnútorným teplom, ktoré vzniká ako dôsledok slapových síl. \n"+
				"Saturnu\n"+
				"\n<b>Život</b> : Z dôvodu zjavnej existencie vody \n"+
				"blízko pod povrchom, Enceladus môže byť aj jedným z.\n"+
				"najlepších miest pre hľadanie mimozemského života\n"
		},
		{"Tethys", 
				"<b>Rovníkový priemer</b>\t\t: 1 062 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.15 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -187°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 1.89 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 1.89 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 295 000 km\n"+
				"\n<b>Základ</b> :Saturnov je piaty najvačší mesiac\n"+
				"Jeho nízka hustota a lesklý povrch naznačujú, že je \n"+
				"tvorený vodným ľadom s malou časťou horniny\n"+
				"\n<b>Kráter</b> :Západnej pologuli dominuje veľký \n"+
				"impaktný kráter, Odysseus, s veľkosťou takmer 2/5 celého \n"+
				"mesiaca. Nie je známe prečo tento dopad mesiac nerozbil, \n"+
				"ale teoretizuje sa, že Tethys bol v čase dopadu v  \n"+
				"čiastočne tekutom stave"
		},
		{"Dione", 
				"<b>Rovníkový priemer</b>\t\t: 1 123 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.23 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -186°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 2.7 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 2.7 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 377 000 km\n"+
				"\n<b>Základ</b> :Je malý saturnov mesiac. Je to však\n"+
				"15 najväčší mesiac v slnečnej sústaveň, hmotnejší ako \n"+
				"všetky menšie mesiace spolu\n"+
				"\n<b>Otočenie</b> :Silne kráterované časti na Dione \n"+
				"sa nečakane nachádzajú na zadnej pologuli, čo vedie k\n"+
				"úvahám, že niektorý z novších dopadov otočil Dione\n"+
				"o 180 stupňov\n"
		},
		{"Rhea", 
				"<b>Rovníkový priemer</b>\t\t: 1 528 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.27 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -200°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 4.5 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 4.5 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 527 000 km\n"+
				"\n<b>Základ</b> :Je druhým najvačším mesiacom.\n"+
				"planéty Saturn a deviatym najvačším mesiacom v \n"+
				"Slnečnej sústave. \n"+
				"\n<b>Obnova povrchu</b> :Prvky na povrchu mesiaca Rhea \n"+
				"môžeme rozdeliť do dvoch oblastí : svetlejšie, silne \n"+
				"kráterované oblasti a oblasti polárnych a rovníkových\n"+
				"častiach. Tento rozdiel naznačuje, že prebehla\n"+		
				"významná obnova povrchu v histórii mesiaca\n"
		},
		{"Titan", 
				"<b>Rovníkový priemer</b>\t\t: 5 152 km\n"+
				"<b>Povrchová gravitácia</b>\t: 1.35 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -179°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 15.9 dňa\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 15.9 dňa\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 1.22 M km\n"+
				"\n<b>Základ</b> : Titan je najväčší meiac Saturna.\n"+
				"a druhý najvačší mesiac Slnečnej sústavy. Je to taktiež \n"+
				"jediný známy prirodzený satelit, ktorý ma hustú .\n"+
				"atmosféru a kvapalný povrch.\n"+
				"\n<b>Jazerá</b> : Dôkazy potvrdujú existenciu tekutých\n"+
				"jazier na Titáne, pričom sa jedná o jediné známe tekuté\n"+
				"jazerá v Slnečnej sústave mimo Zeme\n"+
				"\n<b>Atmosféra</b> : Jedinečná atmosféra Titanu sa z \n"+
				"veľkej časti skladá z dusíka a je trochu hustejšia ako \n"+
				"na Zemi. Atmosféra Titanu sa otáča rýchlejšie než jeho\n"+
				"povrch\n"+
				"\n<b>Život</b> : Predpokladá sa, že Titan sa môže podobať \n"+
				"Zemi v rannej fáze jej vývoja a je tiež jedným z hlavných \n"+
				"kandidátov na možnosť mimozemského života\n"
		},
		{"Iapetus", 
				"<b>Rovníkový priemer</b>\t\t: 1 469 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.22 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -163°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 79 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t:  79 dní\n"+
				"<b>Stredná vzdialenosť</b>\t\t: 3.6 M km\n"+
				"\n<b>Základ</b> : Iapetus je tretí najväčší satelit\n"+
				"Saturnu a 11 najvačší v slnečnej sústave. Jeho \n"+
				"dvojfarebné sfarbenie z neho robí najnezvyčajnejší\n"+
				"zo Saturnových mesiacov\n"+
				"\n<b>Kontrast</b> : Dôkazy potvrdujú existenciu tekutých\n"+
				"jazier na Titáne, pričom sa jedná o jediné známe tekuté\n"+
				"jazerá v Slnečnej sústave mimo Zeme\n"+
				"\n<b>Atmosféra</b> : Terén na prednej pologuli Iapetusu \n"+
				"je jeden z najtmavších v slnečnej sústave. V kontraste,\n"+
				"zadná pologuľa je veľmi svetlá, piričom deliaca čiara\n"+
				"medzi týmito oblasťami je mimoriadne ostrá.\n"
		},
		{"Uranus", 
				"<b>Rovníkový priemer</b>\t\t: 51 800 km\n"+
				"<b>Povrchová gravitácia</b>\t: 8.7 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -210°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 17h 14m\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 84 rokov \n"+
				"<b>Stredná vzdialenosť</b>\t\t: 2 870 M km\n"+
				"\n<b>Základ</b> : Urán je tretia najvačšia planéta z \n"+
				"plynných obrov. Súčasne je to najchladnejšia planéta v\n"+
				"slnečnej sústave\n"+
				"\n<b>Objavenie</b> : Je prvá planéta objavená pomocou\n"+
				"moderného teleskopu, pričom objavenie v roku 1781 je\n"+
				"pripisované anglickému astronómovi Williamovi Hershcelovi\n"+
				"\n<b>Sklon osi</b> : Urán ma naklonenie osi 97.77°, čo\n"+
				"znamená, že sa v pozorovaní s ostatnými planétami okolo\n"+
				"Slnka v podstate valí po boku\n"+
				"\n<b>Pozorovanie</b> : Aj keď sa v opozícii Urán stáva\n"+
				"viditeľný voľným okom, javí sa ako slabá hviezda a to \n"+
				"len za dobrých svetelných podmienok.\n"
		},
		{"Titania", 
				"<b>Rovníkový priemer</b>\t\t: 1 577 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.38 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -200°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 8.7 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 8.7 dní \n"+
				"<b>Stredná vzdialenosť</b>\t\t: 436 000 km\n"+
				"\n<b>Základ</b> : Titania je najväčší mesiac Uránu a\n"+
				"ôsmy najväčší mesiac v slnečnej sústave. Jej povrch\n"+
				"je popretínaný systémom obrovských kaňonov a zrázov\n"
		},
		{"Oberon", 
				"<b>Rovníkový priemer</b>\t\t: 1 523 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.35 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -200°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 13.5 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 13.5 dní \n"+
				"<b>Stredná vzdialenosť</b>\t\t: 583 000 km\n"+
				"\n<b>Základ</b> : Oberon je najvonkajši mesiac a \n"+
				"druhý najväčší z mesiacov Uránu. Jeho tmavočervený\n"+
				"povrch je kráterovaný silnejšie než povrch iných\n"+
				"hlavných Uránových mesiacov\n"
		},
		{"Neptune", 
				"<b>Rovníkový priemer</b>\t\t: 49 500 km\n"+
				"<b>Povrchová gravitácia</b>\t: 11.2 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -200°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 16h 06m\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 165 rokov \n"+
				"<b>Stredná vzdialenosť</b>\t\t: 4500 M km\n"+
				"\n<b>Základ</b> : Neptún je oficiálne najvzdialenejšia\n"+
				"planéta od Slnka. je to najmenší ale najhustejší \n"+
				"plynný obor. Neptún má povrchovú gravitáciu, ktorú\n"+
				"prekonáva len Jupiter\n"+
				"\n<b>Objavenie</b> : Neptún bola prvá  planéta \n"+
				"objavená čisto na základe matematicke predikcie, nie \n"+
				"priamym pozorovaním. Vzhľadom k tomu, že bol objavený\n"+
				"v roku 1846, dokončil odvtedy iba jeden obeh okolo\n"+
				"Slnka\n"
		},
		{"Triton", 
				"<b>Rovníkový priemer</b>\t\t: 2 707 km\n"+
				"<b>Povrchová gravitácia</b>\t: 0.78 m/s²\n"+
				"<b>Povrchová teplota</b>\t\t\t: -235°C\n"+
				"<b>Doba rotácie</b>\t\t\t\t\t: 5.9 dní\n"+
				"<b>Doba obehu</b>\t\t\t\t\t: 5.9 dní \n"+
				"<b>Stredná vzdialenosť</b>\t\t: 335 000 km\n"+
				"\n<b>Základ</b> : Triton je najvačší mesiac\n"+
				"Neptúnu. Je to rovnako najväčší mesiac v Slnečnej\n"+
				"sústave, ktorý obieha v opačnom smere ako je rotácia\n"+
				"prekonáva len Jupiter\n"+ 
				"\n<b>Chlad</b> : Z dôvodu vysokej odrazivosti je\n"+
				"Triton jedným z najchladnejších objektov v Slnečnej\n"+
				"sústave\n"+
				"\n<b>Aktivita</b> : Triton, Io a Venuša sú popri Zemi\n"+
				"jediné telesá v slnečnej sústave, kde v súčasnosti\n"+
				"prebie vulkanická aktivita\n"
		}
	};

	public static string Get(string name){
		if ( info.ContainsKey( name ) ){
			return info[name];
		}
		return null;
	}
}
